[package]
name = "nanogpt-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.9.0-alpha.1" }
rand = { version = "0.9.0", features = ["std"] }
rand_pcg = "0.9.0"
